### PR TITLE
Make numpy optional

### PR DESCRIPTION
**Pull request by utapyngo**
Refactor cutil.pyx to avoid repetitions
Fix docstrings

### CODE REVIEW

**Comment by utapyngo** [comment]
stryd/fetch-release-asset requires an access token to get `rustlib.zip`, that's why the checks are failing.

**Comment by utapyngo** [comment]
@urschrei could you please review this?

**Comment by utapyngo** [comment]
@urschrei who can review this?

**Comment by utapyngo** [comment]
@urschrei The tests have passed: https://github.com/utapyngo/simplification/runs/5641757985

**Comment by urschrei** [comment]
Hi @utapyngo, sorry for the delay at my end. I'll try to find time for a proper review this week, but in general these changes look good. I need to have a look at some details around Numpy installation and benchmarks, but we should be able to merge if those are OK.

**Comment by utapyngo** [comment]
@urschrei I have removed Cython from `install_requires` as it does not seem to be required for `simplification` to work.
Am I correct?

**Comment by utapyngo** [comment]
@urschrei could you please review?

**Comment by urschrei** [comment]
Hi @utapyngo could you rebase against `master`, and then let's see about merging this…

**Comment by utapyngo** [comment]
> Hi @utapyngo could you rebase against `master`, and then let's see about merging this…

Done.

**Comment by utapyngo** [comment]
Anyone here?

**Pull request merged**
